### ISSUE TITLE
[Bug]: modules.netbox_l2vpn

### ISSUE THREAD

**Issue by cse-sa** [netbox-community/ansible_modules#1351]
### Ansible NetBox Collection version

v3.20.0

### Ansible version

```bash
ansible [core 2.14.16]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Aug 26 2024, 07:20:54) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### NetBox version

v4.0.11 and v4.1.3

### Python version

3.11

### Steps to Reproduce

```yaml
 - name: playbook
   hosts: localhost
   gather_facts: no

   vars:
     NETBOX_ENDPOINT: "https://netboxtest.test.de"
     NETBOX_TOKEN: ""

   vars_files:
     - "varsvlan.yml"

   tasks:
     - name: Create L2VPN with all required information
       netbox.netbox.netbox_l2vpn:
         netbox_url: "{{ NETBOX_ENDPOINT }}"
         netbox_token: "{{ NETBOX_TOKEN }}"
         data:
           name: "L2-VNI-5{{ vlan_id }}{{ vlan_suffix }}"
           type: "vxlan"
           identifier: "5{{ vlan_id }}"
           tenant: "{{ tenant_name }}"
           description: "L2-VNI-{{ vlan_id }}{{ vlan_suffix }}"
         state: present
```

### Expected Behavior

Create L2VPNs in Netbox

### Observed Behavior

Wrong API mapping in the modul,
maybe somthing of the entpoint change ?
https://github.com/netbox-community/ansible_modules/commit/71119422fba7863386aad009fb734481477f5da6

TASK [Create L2VPN with all required information] *********************************************************************************************
task path: /root/pb_create_vlanl2vpn.yml:45
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571 `" && echo ansible-tmp-1730962539.020026-73456-25600872828571="` echo /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/netbox/netbox/plugins/modules/netbox_l2vpn.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-734008mnwibv9/tmp1ppf1wgf TO /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/ /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_l2vpn', init_globals=dict(_module_fqn='ansible_collections.netbox.netbox.plugins.modules.netbox_l2vpn', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_l2vpn.py", line 204, in <module>
  File "/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_l2vpn.py", line 200, in main
  File "/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_vpn.py", line 44, in run
AttributeError: 'Api' object has no attribute 'vpn'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1730962539.020026-73456-25600872828571/AnsiballZ_netbox_l2vpn.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.netbox.netbox.plugins.modules.netbox_l2vpn', init_globals=dict(_module_fqn='ansible_collections.netbox.netbox.plugins.modules.netbox_l2vpn', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_l2vpn.py\", line 204, in <module>\n  File \"/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/modules/netbox_l2vpn.py\", line 200, in main\n  File \"/tmp/ansible_netbox.netbox.netbox_l2vpn_payload_yqxn3p_x/ansible_netbox.netbox.netbox_l2vpn_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_vpn.py\", line 44, in run\nAttributeError: 'Api' object has no attribute 'vpn'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

**Comment by rodvand** [comment]
Make sure you have an updated pynetbox.

**Comment by cse-sa** [comment]
thanks @rodvand 
i was running 7.0.0
after upgrade to 7.4.1 it works now!
